[project]
name = "flugmodus-backend"
version = "0.1.0"
description = "'Secure' offline payments and 'settlement'. Cofinpro Coding Dojo 2026 :)"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cryptography>=50.0.1",
    "fastapi[standard]>=0.141.1",
    "sqlmodel>=0.0.47",
    "ruff>=0.16.9",
    "sqladmin>=0.32.0",
    "segno>=1.6.6",
]

[tool.fastapi]
entrypoint = "main:app"
[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
]
